### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [PercussiveElbow/crobat-sdk-crystal#2]
When running with docker, i get the following error
```SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed```

**Comment by PercussiveElbow** [comment]
Weird, the BusyBox container no longer seemed to be using the ca-certs I supply from the builder container. I've merged #3 which fixes this issue on my side. Try a fresh pull and rebuild, it still doesn't work let me know and I can take a look.

**Comment by ghost** [comment]
Its fixed and working.
Thanks
