### ISSUE TITLE
Search by tld

### ISSUE THREAD

**Issue by ghost** [PercussiveElbow/crobat-sdk-crystal#8]
Can you integrate the option to search by tld. Say eg all .mil domains

**Comment by PercussiveElbow** [comment]
This is something that would have to be implemented first on the API side at https://github.com/Cgboal/SonarSearch

If Calum adds support for TLD searching I'm happy to add that to this SDK and the client. 

In regards to the query about searching specifically for .mil  hosts, just make sure whatever you're doing is legal and above board. A Blackhawk ride to Gitmo is probably one of the less fun vacations even if it does come with a free jumpsuit.

**Comment by ghost** [comment]
hahaha..

They have a VDP on [Hackerone](https://hackerone.com/deptofdefense).
